## Numpy Arrays

In [2]:
!pip install numpy

In [13]:
my_list = [1,2,3]

In [14]:
my_list

[1, 2, 3]

In [17]:
import numpy as np

In [18]:
arr = np.array(my_list)

In [19]:
arr

array([1, 2, 3])

In [21]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [22]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [23]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [27]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [28]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [30]:
np.zeros(3)

array([0., 0., 0.])

In [33]:
np.zeros((3,3)) #rXc

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.zeros(3,3)

TypeError: Cannot interpret '3' as a data type

In [34]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [36]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [39]:
np.eye(3) #rXC

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
np.linspace(0,5,10) # Starting, Stop, how many data I want

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [42]:
np.linspace(100,500,10) 

array([100.        , 144.44444444, 188.88888889, 233.33333333,
       277.77777778, 322.22222222, 366.66666667, 411.11111111,
       455.55555556, 500.        ])

In [43]:
np.linspace(0,1,100) 

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [44]:
np.random.rand(5)

array([0.95830911, 0.91574954, 0.32241913, 0.57710849, 0.49390666])

In [49]:
np.random.rand(3,5) #rXC

array([[0.59948007, 0.94408416, 0.0539356 , 0.66543594, 0.27949267],
       [0.22374943, 0.80455008, 0.92802876, 0.21111155, 0.53345762],
       [0.59995699, 0.73943113, 0.37515009, 0.0679755 , 0.40866163]])

In [50]:
np.random.randn(5)

array([ 0.45224889, -0.45524647, -1.76799065,  0.48035381, -2.02563255])

In [51]:
np.random.randn(3,5)

array([[ 2.7832178 ,  0.65670644,  1.62549934,  1.064463  , -1.2747648 ],
       [-1.75091016,  0.04145425,  0.11207236, -1.89989691, -0.37464574],
       [ 0.4945229 ,  0.37897338, -1.37981792, -0.2701666 ,  0.75497138]])

In [52]:
np.random.randint(1,100)

59

In [53]:
np.random.randint(1,100,30)

array([ 3, 18, 70,  7, 16,  9, 63, 56, 86,  8, 11, 23, 44, 79, 39, 99, 50,
       37,  5,  2, 94, 67,  2, 87, 80, 40, 64, 35,  1, 15])

In [60]:
arr = np.arange(1,100,2) # start, stop, step

In [61]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [62]:
ranarr = np.random.randint(0,50,10)

In [63]:
ranarr

array([35,  0,  2, 26, 44, 48, 43,  8, 48, 20])

In [68]:
ranarr.shape

(10,)

In [75]:
ranarr.reshape(5,2)

array([[35,  0],
       [ 2, 26],
       [44, 48],
       [43,  8],
       [48, 20]])

In [74]:
ranarr

array([35,  0,  2, 26, 44, 48, 43,  8, 48, 20])

In [71]:
arr.shape

(50,)

In [79]:
arr.reshape(5,10)

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

In [80]:
ranarr

array([35,  0,  2, 26, 44, 48, 43,  8, 48, 20])

In [76]:
ranarr.max()

48

In [77]:
ranarr.min()

0

In [81]:
ranarr.argmax() #max index

5

In [83]:
ranarr.argmin() #min index

1

In [84]:
type(12)

int

In [85]:
arr.dtype

dtype('int64')

In [86]:
from numpy.random import randint

In [87]:
randint(2,10)

2

## Numpy Array Indexing

In [94]:
arr = np.arange(0,10)

In [95]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
arr[8]

8

In [97]:
arr[1:5] # starting index, stop postion

array([1, 2, 3, 4])

In [98]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [99]:
arr[0:5] = 100

In [100]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [128]:
arr2 = np.arange(0,10)

In [129]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
s_arr = arr2[0:5]

In [131]:
s_arr

array([0, 1, 2, 3, 4])

In [132]:
s_arr[::] = 100

In [133]:
s_arr

array([100, 100, 100, 100, 100])

In [134]:
arr2

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [135]:
#### copy array

In [136]:
arr_copy = arr2.copy()

In [137]:
arr_copy[0:5] = 500

In [138]:
arr2

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [139]:
arr_copy

array([500, 500, 500, 500, 500,   5,   6,   7,   8,   9])

In [140]:
### 2D Array

In [141]:
arr_2d = np.array([[10,25,75],[37,49,21],[8,34,21]])

In [151]:
arr_2d

array([[10, 25, 75],
       [37, 49, 21],
       [ 8, 34, 21]])

In [153]:
arr_2d[0] # First Row

array([10, 25, 75])

In [147]:
arr_2d[0][1] # rXc

25

In [154]:
arr_2d[1] # Seond row

array([37, 49, 21])

In [149]:
arr_2d[1][2]

21

In [150]:
arr_2d

array([[10, 25, 75],
       [37, 49, 21],
       [ 8, 34, 21]])

In [156]:
arr_2d[:2] #Row

array([[10, 25, 75],
       [37, 49, 21]])

In [162]:
arr_2d[0:2, 1:3]

array([[25, 75],
       [49, 21]])

In [163]:
arr_2d[:2, 1:]

array([[25, 75],
       [49, 21]])

In [165]:
arr_2d[1:, :2]

array([[37, 49],
       [ 8, 34]])

In [167]:
arr2 = np.arange(0,10)

In [168]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [169]:
arr2 >5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [170]:
arr2[arr2 >5]

array([6, 7, 8, 9])

In [171]:
arr_2d = np.arange(50).reshape(5,10)

In [172]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [174]:
arr_2d[2:4, 5:7]

array([[25, 26],
       [35, 36]])

## Numpy Operation

In [175]:
arr = np.arange(0,11)

In [176]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [177]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [178]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [179]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [180]:
arr/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [181]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [182]:
arr/arr

/tmp/ipykernel_16008/1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [183]:
1/0

ZeroDivisionError: division by zero

In [184]:
1/arr

/tmp/ipykernel_16008/255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [185]:
arr/1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [186]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [187]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [188]:
np.max(arr)

10

In [189]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [190]:
np.log(arr)

/tmp/ipykernel_16008/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])