## Numpy Arrays

In [2]:
!pip install numpy

In [13]:
my_list = [1,2,3]

In [14]:
my_list

[1, 2, 3]

In [17]:
import numpy as np

In [18]:
arr = np.array(my_list)

In [19]:
arr

array([1, 2, 3])

In [21]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [22]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [23]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [27]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [28]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [30]:
np.zeros(3)

array([0., 0., 0.])

In [33]:
np.zeros((3,3)) #rXc

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.zeros(3,3)

TypeError: Cannot interpret '3' as a data type

In [34]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [36]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [39]:
np.eye(3) #rXC

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
np.linspace(0,5,10) # Starting, Stop, how many data I want

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [42]:
np.linspace(100,500,10) 

array([100.        , 144.44444444, 188.88888889, 233.33333333,
       277.77777778, 322.22222222, 366.66666667, 411.11111111,
       455.55555556, 500.        ])

In [43]:
np.linspace(0,1,100) 

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [44]:
np.random.rand(5)

array([0.95830911, 0.91574954, 0.32241913, 0.57710849, 0.49390666])

In [49]:
np.random.rand(3,5) #rXC

array([[0.59948007, 0.94408416, 0.0539356 , 0.66543594, 0.27949267],
       [0.22374943, 0.80455008, 0.92802876, 0.21111155, 0.53345762],
       [0.59995699, 0.73943113, 0.37515009, 0.0679755 , 0.40866163]])

In [50]:
np.random.randn(5)

array([ 0.45224889, -0.45524647, -1.76799065,  0.48035381, -2.02563255])

In [51]:
np.random.randn(3,5)

array([[ 2.7832178 ,  0.65670644,  1.62549934,  1.064463  , -1.2747648 ],
       [-1.75091016,  0.04145425,  0.11207236, -1.89989691, -0.37464574],
       [ 0.4945229 ,  0.37897338, -1.37981792, -0.2701666 ,  0.75497138]])

In [52]:
np.random.randint(1,100)

59

In [53]:
np.random.randint(1,100,30)

array([ 3, 18, 70,  7, 16,  9, 63, 56, 86,  8, 11, 23, 44, 79, 39, 99, 50,
       37,  5,  2, 94, 67,  2, 87, 80, 40, 64, 35,  1, 15])

In [60]:
arr = np.arange(1,100,2) # start, stop, step

In [61]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [62]:
ranarr = np.random.randint(0,50,10)

In [63]:
ranarr

array([35,  0,  2, 26, 44, 48, 43,  8, 48, 20])

In [68]:
ranarr.shape

(10,)

In [75]:
ranarr.reshape(5,2)

array([[35,  0],
       [ 2, 26],
       [44, 48],
       [43,  8],
       [48, 20]])

In [74]:
ranarr

array([35,  0,  2, 26, 44, 48, 43,  8, 48, 20])

In [71]:
arr.shape

(50,)

In [79]:
arr.reshape(5,10)

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

In [80]:
ranarr

array([35,  0,  2, 26, 44, 48, 43,  8, 48, 20])

In [76]:
ranarr.max()

48

In [77]:
ranarr.min()

0

In [81]:
ranarr.argmax() #max index

5

In [83]:
ranarr.argmin() #min index

1

In [84]:
type(12)

int

In [85]:
arr.dtype

dtype('int64')

In [86]:
from numpy.random import randint

In [87]:
randint(2,10)

2

## Numpy Array Indexing