# Numpy Arrays

In [2]:
my_list=[1,2,3]

In [3]:
my_list

[1, 2, 3]

In [4]:
import numpy as np

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [8]:
my_mat= [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((5,5)) # rxc

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones(4)

array([1., 1., 1., 1.])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [20]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(5)

array([0.70339822, 0.35933206, 0.02368885, 0.12066019, 0.75221324])

In [23]:
np.random.rand(5,5)

array([[0.2807634 , 0.03002415, 0.32007303, 0.37527761, 0.3757337 ],
       [0.25360107, 0.26549185, 0.04749412, 0.15259467, 0.63166038],
       [0.93149247, 0.83893059, 0.71328834, 0.17737858, 0.32547562],
       [0.3416548 , 0.40906092, 0.70191416, 0.71817696, 0.66365412],
       [0.56218462, 0.74385882, 0.25339115, 0.96841461, 0.28244036]])

In [24]:
np.random.randn(2)

array([ 2.31074779, -1.46398039])

In [25]:
np.random.randn(4,4)

array([[-0.44854502,  2.91377538,  0.89083757,  0.62138792],
       [ 0.95666084,  0.68976781, -0.42960065, -1.21046854],
       [-0.14893508, -0.86160743,  0.85249331,  1.39258713],
       [ 2.40540444,  0.85909283,  0.02674806, -2.57076414]])

In [26]:
np.random.randint(1,100)

16

In [27]:
np.random.randint(1,100,10)

array([ 4, 50,  1, 45, 58, 42, 56, 65, 26, 68])

In [28]:
arr = np.arange(25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
ranarr= np.random.randint(0,50,10)

In [31]:
ranarr

array([27, 20, 13,  9, 34, 15, 34, 22,  0, 27])

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr

array([27, 20, 13,  9, 34, 15, 34, 22,  0, 27])

In [34]:
ranarr.max()

np.int64(34)

In [37]:
print(ranarr.min())

0


In [38]:
ranarr

array([27, 20, 13,  9, 34, 15, 34, 22,  0, 27])

In [39]:
ranarr.argmax()

np.int64(4)

In [40]:
ranarr.argmin()

np.int64(8)

In [43]:
arr.shape

(25,)

In [44]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
arr = arr.reshape(5,5)

In [46]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arr.dtype

dtype('int64')